version: '3.7'
services:
  digidex_front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digidex_front
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    networks:
      - digidex-network
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  digidex-network:
    driver: bridge
